apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetframeworkdocker-deployment
  labels:
    app: dotnetframeworkdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetframeworkdocker
  template:
    metadata:
      labels:
        app: dotnetframeworkdocker
    spec:
      containers:
        - name: dotnetframeworkdocker
          image: anujangooral/dotnetframework_docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetframeworkdocker-service
spec:
  type: NodePort
  selector:
    app: dotnetframeworkdocker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000