name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login --username AnujAngooral --password ThzHd*g7Gj#t2](
    - name: Build the Docker image
      run: docker build --tag my-image-name:$(date +%s) --file ./dotnetframework_docker/Dockerfile . 
